"""Persona Studio — Complete End-to-End Workflow Test.

This test runs the ENTIRE mock workflow as specified in the master prompt:

    create persona
    → generate identity candidates
    → approve identity
    → build reference dataset
    → train mock LoRA
    → validate identity
    → create voice
    → create shoot
    → generate images
    → generate video
    → QA
    → assemble content pack
    → calendar
    → analytics
    → 24-month forecast
"""

import asyncio
import pytest
from uuid import UUID


@pytest.mark.asyncio
async def test_full_e2e_workflow(client):
    """The complete Persona Studio workflow — all phases, all mocks."""

    # ═══════════════════════════════════════════════════════════════
    # PHASE 1-3: Create Persona
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 1-3: Creating Persona ===")

    import time
    unique_name = f"E2E_Ava_{int(time.time()*1000)}"
    resp = await client.post("/api/v1/personas", json={
        "name": unique_name,
        "age": 24,
        "description": "Luxury lifestyle synthetic creator",
        "adult_verified": True,
        "synthetic_identity": True,
        "appearance": {
            "hair": "long blonde",
            "hair_length": "long",
            "hair_colour": "blonde",
            "eye_colour": "blue",
            "facial_characteristics": "high cheekbones",
            "skin_characteristics": "fair",
            "body_characteristics": "athletic",
            "height_profile": "5'7\"",
            "identifying_synthetic_features": "distinctive smile",
            "style_preferences": ["luxury", "lifestyle"],
        },
        "personality": ["confident", "playful"],
        "brand": "luxury lifestyle",
        "voice_style": "South African English",
        "publishing_frequency": "5 packs/week",
    })
    assert resp.status_code in (200, 201), f"Create persona failed: {resp.text}"
    persona = resp.json()
    persona_id = persona["id"]
    job_id = persona.get("job_id")
    assert persona["name"] == unique_name
    assert persona["age"] == 24
    print(f"  ✓ Persona created: {persona_id}")

    # Wait for background workflow to finish
    if job_id:
        for _ in range(100):  # max 30s
            await asyncio.sleep(0.3)
            jr = await client.get(f"/api/v1/jobs/{job_id}")
            if jr.status_code == 200 and jr.json()["status"] in ("completed", "failed"):
                break
        # Re-fetch persona
        fr = await client.get(f"/api/v1/personas/{persona_id}")
        persona = fr.json()
    assert persona["status"] in ("active", "building")

    # Verify persona appears in list
    resp = await client.get("/api/v1/personas")
    assert resp.status_code == 200
    assert len(resp.json()) >= 1
    print(f"  ✓ Persona appears in list")

    # Verify identities were generated by workflow
    resp = await client.get(f"/api/v1/personas/{persona_id}/identities")
    assert resp.status_code == 200
    identities = resp.json()
    assert len(identities) >= 1, "No identities generated"
    print(f"  ✓ {len(identities)} identity candidates generated")

    # Approve the best identity
    identity_id = identities[0]["id"]
    resp = await client.post(f"/api/v1/personas/{persona_id}/identities/{identity_id}/approve")
    assert resp.status_code == 200
    print(f"  ✓ Identity approved: {identity_id}")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 4: Workflow Engine
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 4: Workflow Engine ===")

    resp = await client.get("/api/v1/workflows")
    assert resp.status_code == 200
    workflows = resp.json()
    assert len(workflows) >= 1
    print(f"  ✓ {len(workflows)} workflows running")

    for wf in workflows:
        print(f"    - {wf['name']}: {wf['status']}")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 9: Create Shoot
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 9: Creating Shoot ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/shoots", json={
        "name": "Sunday at Home",
        "theme": "relaxed lifestyle",
        "image_count": 8,
    })
    assert resp.status_code == 200
    shoot = resp.json()
    shoot_id = shoot["id"]
    print(f"  ✓ Shoot created: {shoot_id}")

    # Generate shoot content
    resp = await client.post(f"/api/v1/shoots/{shoot_id}/generate")
    assert resp.status_code == 200
    print(f"  ✓ Shoot generation started: {resp.json()['workflow_id']}")

    # Verify shoots list
    resp = await client.get(f"/api/v1/personas/{persona_id}/shoots")
    assert resp.status_code == 200
    assert len(resp.json()) >= 1

    # ═══════════════════════════════════════════════════════════════
    # PHASE 9: Content Pack
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 9: Content Pack ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/packs", json={
        "name": "Sunday At Home Pack",
        "platform": "instagram",
    })
    assert resp.status_code == 200
    pack = resp.json()
    pack_id = pack["id"]
    print(f"  ✓ Content pack created: {pack_id}")

    # Assemble the pack (generates images, video, voice, QA, captions)
    resp = await client.post(f"/api/v1/packs/{pack_id}/assemble")
    assert resp.status_code == 200
    print(f"  ✓ Pack assembly started: {resp.json()['workflow_id']}")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 7: QA Results
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 7: QA Results ===")

    resp = await client.get(f"/api/v1/personas/{persona_id}/qa")
    assert resp.status_code == 200
    qa_results = resp.json()
    print(f"  ✓ {len(qa_results)} QA results")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 10: Content Calendar / Scheduling
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 10: Content Calendar ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/schedule/generate")
    assert resp.status_code == 200
    schedule = resp.json()
    print(f"  ✓ Scheduled {schedule['scheduled']} posts")

    resp = await client.get(f"/api/v1/personas/{persona_id}/schedule")
    assert resp.status_code == 200
    posts = resp.json()
    print(f"  ✓ {len(posts)} posts in schedule")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 10: Autopilot
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 10: Autopilot ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/autopilot?mode=assisted")
    assert resp.status_code == 200
    print(f"  ✓ Autopilot mode: {resp.json()['autopilot']}")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 11: Analytics
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 11: Analytics ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/analytics/generate")
    assert resp.status_code == 200
    print(f"  ✓ Analytics generated: {resp.json()['days']} days")

    resp = await client.get(f"/api/v1/personas/{persona_id}/analytics")
    assert resp.status_code == 200
    analytics = resp.json()
    assert len(analytics) == 90
    print(f"  ✓ {len(analytics)} analytics snapshots")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 12: 24-Month Forecast
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 12: 24-Month Forecast ===")

    resp = await client.post(f"/api/v1/personas/{persona_id}/forecasts/generate")
    assert resp.status_code == 200
    print(f"  ✓ Forecast generated: {resp.json()['horizon_months']} months")

    resp = await client.get(f"/api/v1/personas/{persona_id}/forecasts")
    assert resp.status_code == 200
    forecasts = resp.json()
    assert len(forecasts) >= 1
    forecast = forecasts[0]
    assert len(forecast["scenarios"]) == 3  # conservative, base, aggressive
    assert len(forecast["scenarios"][0]["monthly_followers"]) == 24
    print(f"  ✓ 3 scenarios: {', '.join(s['scenario'] for s in forecast['scenarios'])}")
    print(f"  ✓ 24-month projections for each scenario")

    # ═══════════════════════════════════════════════════════════════
    # PHASE 5-8: Verify Mock Providers
    # ═══════════════════════════════════════════════════════════════
    print("\n=== PHASE 5-8: Provider Verification ===")

    from app.providers.mocks import (
        MockImageProvider, MockVideoProvider, MockVoiceProvider, MockTrainerProvider
    )

    # Image
    img = MockImageProvider()
    r = await img.generate(prompt="test", seed=42)
    assert r.success and r.data["is_mock"]
    print("  ✓ MockImageProvider working")

    # Video
    vid = MockVideoProvider()
    r = await vid.text_to_video(prompt="test")
    assert r.success and r.data["is_mock"]
    print("  ✓ MockVideoProvider working")

    # Voice
    v = MockVoiceProvider()
    r = await v.create_voice(name="test")
    assert r.success
    r = await v.synthesize(text="Hello", voice_id=r.data["voice_id"])
    assert r.success and r.data["is_mock"]
    print("  ✓ MockVoiceProvider working")

    # Trainer
    t = MockTrainerProvider()
    r = await t.train(dataset_id="test")
    assert r.success and r.data["is_mock"]
    print("  ✓ MockTrainerProvider working")

    # ═══════════════════════════════════════════════════════════════
    # SUMMARY
    # ═══════════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("PERSONA STUDIO — E2E WORKFLOW COMPLETE")
    print("=" * 60)
    print(f"  Persona: {unique_name} ({persona_id})")
    print(f"  Identity: {identity_id}")
    print(f"  Shoot: {shoot_id}")
    print(f"  Content Pack: {pack_id}")
    print(f"  Workflows: {len(workflows)}")
    print(f"  QA Results: {len(qa_results)}")
    print(f"  Scheduled Posts: {len(posts)}")
    print(f"  Analytics Snapshots: {len(analytics)}")
    print(f"  Forecast Scenarios: {len(forecast['scenarios'])}")
    print("=" * 60)
