"""Persona Studio — the fan-facing API.

Everything a paying visitor can reach. Every route requires a session cookie
(`require_user` / `require_fan`), and every route writes an audit row, so
`GET /fan/activity` is a real record of what happened rather than a summary
assembled after the fact.

Three properties this surface is built to have, in order of importance:

  1. **Nothing is invented.** If no LLM answers, the chat endpoint returns 503.
     There is no fallback text anywhere in this file.
  2. **Money moves once.** Unlocks are idempotent on the ledger's
     `ppv:{user}:{product}` key *and* on a unique constraint on entitlements.
  3. **Access is checked at serve time.** The media route re-asks the
     entitlements table on every request; a URL that worked yesterday does not
     work for someone who never paid.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app import paths
from app.auth import audit, require_fan, require_user
from app.billing import service as billing
from app.billing.entitlements import active_subscription, check_access
from app.billing.ledger import integrity_report
from app.character import load_character, merged_character
from app.chat_engine import LLMUnavailable, generate_chat_reply
from app.database import get_db
from app.models import (
    AccessEvent, AppUser, AuditEvent, FanAccount, FanConversation, Persona,
    Product, ProductMedia, SubscriptionPlan, Wallet, utcnow,
)
from app.providers.registry import get_registry

router = APIRouter()

STORAGE_DIR = paths.STORAGE_ROOT

AI_DISCLOSURE = (
    "This creator is an AI character. She is not a human being, and the "
    "conversation you are having is generated by a language model. The photos "
    "and videos are synthetic. Nothing here is a real person."
)
SIMULATED_MONEY_NOTICE = (
    "Balances and purchases in this app are simulated. No real money is "
    "charged, no card is stored, and nothing here can be redeemed for cash."
)


# ── helpers ───────────────────────────────────────────────────────────

async def _persona_for(db: AsyncSession, link: FanAccount) -> Persona:
    from uuid import UUID

    try:
        persona = await db.get(Persona, UUID(str(link.persona_id)))
    except ValueError:
        persona = None
    if persona is None:
        raise HTTPException(409, "The assigned persona no longer exists")
    return persona


async def _wallet(db: AsyncSession, user_id: str) -> Wallet:
    wallet = (
        await db.execute(select(Wallet).where(Wallet.user_id == user_id))
    ).scalar_one_or_none()
    if wallet is None:
        wallet = Wallet(user_id=user_id, balance_minor=0)
        db.add(wallet)
        await db.flush()
    return wallet


async def _product(db: AsyncSession, product_id: str) -> Product:
    product = await db.get(Product, product_id)
    if product is None:
        raise HTTPException(404, "That content does not exist")
    return product


def _start_provider_names() -> list[str]:
    """The providers a new conversation may be pinned to.

    A test fake has no chain and returns [], in which case the provider picks
    whatever it has configured.
    """
    provider = get_registry().resolve_optional("llm")
    return list(getattr(provider, "member_names", []) or [])


async def _conversation(db: AsyncSession, link: FanAccount) -> FanConversation:
    """The fan's open thread, created on first use.

    Created with `served_by` already chosen, by rotating on how many
    conversations this fan has had — so the two live models genuinely share the
    live chat, while a single conversation never hears two voices. See
    app/providers/fallback_llm.py.
    """
    row = (
        await db.execute(
            select(FanConversation)
            .where(
                FanConversation.fan_id == link.fan_id,
                FanConversation.status == "open",
            )
            .order_by(FanConversation.created_at.desc())
            .limit(1)
        )
    ).scalars().first()
    if row is not None:
        return row

    previous = (
        await db.execute(
            select(func.count()).select_from(FanConversation).where(
                FanConversation.fan_id == link.fan_id
            )
        )
    ).scalar() or 0

    names = _start_provider_names()
    served_by = names[previous % len(names)] if names else ""

    row = FanConversation(
        fan_id=link.fan_id, persona_id=str(link.persona_id), served_by=served_by
    )
    db.add(row)
    await db.flush()
    return row


async def _thread_messages(db: AsyncSession, fan_id: str, limit: int = 60) -> list[dict]:
    # The tiebreak is load-bearing. A fan's message and her reply are written
    # in the same transaction, and were written with the same `created_at`, so
    # the database was free to return them in either order — the thread could
    # render as her answering before the question. Ordering by created_at and
    # then inbound-first makes the order defined even for the rows already
    # written that way. (The writer now also stamps the reply a microsecond
    # later; this handles the rows that predate that.)
    rows = (
        await db.execute(
            text(
                "SELECT id, direction, content, message_type, is_ai_generated, "
                "is_ppv, ppv_price, ppv_unlocked, intent, metadata_json, created_at "
                "FROM chat_messages WHERE fan_id = :fid "
                "ORDER BY created_at DESC, (direction = 'inbound') ASC "
                "LIMIT :limit"
            ),
            {"fid": fan_id, "limit": limit},
        )
    ).fetchall()

    out = []
    for row in reversed(rows):
        metadata = row[9]
        if isinstance(metadata, str):
            try:
                metadata = json.loads(metadata or "{}")
            except json.JSONDecodeError:
                metadata = {}
        out.append({
            "id": row[0],
            "direction": row[1],
            "content": row[2],
            "message_type": row[3],
            "is_ai_generated": bool(row[4]),
            "is_ppv": bool(row[5]),
            "ppv_price": row[6],
            "ppv_unlocked": bool(row[7]),
            "intent": row[8],
            "served_by": (metadata or {}).get("served_by", ""),
            "created_at": row[10].isoformat() if hasattr(row[10], "isoformat") else str(row[10]),
        })
    return out


async def _log_access(
    db: AsyncSession, *, user_id: str | None, product_id: str | None,
    allowed: bool, reason: str,
) -> None:
    db.add(AccessEvent(
        user_id=user_id, product_id=product_id, allowed=allowed, reason=reason
    ))
    await db.flush()


# ── persona ───────────────────────────────────────────────────────────

@router.get("/fan/persona")
async def get_persona(
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    persona = await _persona_for(db, link)
    stored = await load_character(db, str(persona.id))
    character = merged_character(persona.name, persona.brand or "", stored)

    return {
        "id": str(persona.id),
        "name": persona.name,
        "age": persona.age,
        "brand": persona.brand or "",
        "avatar_url": persona.avatar_url or "",
        "bio": character["backstory"],
        "synthetic_identity": bool(persona.synthetic_identity),
        "disclosure": AI_DISCLOSURE,
        "disclosure_is_ai": True,
        "money_notice": SIMULATED_MONEY_NOTICE,
    }


# ── chat ──────────────────────────────────────────────────────────────

@router.get("/fan/thread")
async def get_thread(
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    return {
        "messages": await _thread_messages(db, link.fan_id),
        "disclosure": AI_DISCLOSURE,
    }


class MessageRequest(BaseModel):
    text: str


@router.post("/fan/messages")
async def send_message(
    payload: MessageRequest,
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    """Send a message and get her reply.

    Returns 503 when no provider in the chain can answer. It does not return a
    placeholder — see the module docstring.
    """
    text_in = (payload.text or "").strip()
    if not text_in:
        raise HTTPException(422, "Message text is required")
    if len(text_in) > 4000:
        raise HTTPException(422, "Message is too long (4000 characters max)")

    persona = await _persona_for(db, link)
    history = await _thread_messages(db, link.fan_id, limit=10)
    conversation = await _conversation(db, link)

    stored = await load_character(db, str(persona.id))
    character = merged_character(persona.name, persona.brand or "", stored)

    fan_row = (
        await db.execute(
            text(
                "SELECT total_spent, ppv_purchases, messages_sent, last_active "
                "FROM fans WHERE id = :fid"
            ),
            {"fid": link.fan_id},
        )
    ).fetchone()
    total_spent = float(fan_row[0] or 0) if fan_row else 0.0
    ppv_purchases = int(fan_row[1] or 0) if fan_row else 0
    messages_sent = int(fan_row[2] or 0) if fan_row else 0
    days_since = 0
    if fan_row and fan_row[3]:
        last_active = fan_row[3]
        if last_active.tzinfo is None:
            last_active = last_active.replace(tzinfo=timezone.utc)
        days_since = max(0, (utcnow() - last_active).days)

    now = utcnow()

    try:
        reply = await generate_chat_reply(
            persona_name=persona.name,
            brand=persona.brand or "lifestyle",
            personality=json.dumps(persona.personality) if persona.personality else "friendly, warm",
            voice_style=persona.voice_style or "casual",
            fan_message=text_in,
            conversation_history=history,
            fan_total_spent=total_spent,
            fan_ppv_purchases=ppv_purchases,
            fan_messages_sent=messages_sent,
            days_since_last_active=days_since,
            character=character,
            preferred_provider=conversation.served_by or None,
        )
    except LLMUnavailable as exc:
        # The 503 is the honest outcome. Nothing was written.
        raise HTTPException(
            503,
            "She can't reply right now — no language model is available. "
            f"Nothing was sent. ({exc})",
        )

    inbound_id = str(__import__("uuid").uuid4())
    outbound_id = str(__import__("uuid").uuid4())

    # Her reply happened after the fan's message, and the row should say so.
    # Writing both with the same `now` made the thread's order undefined.
    reply_at = now + timedelta(microseconds=1)

    await db.execute(
        text(
            "INSERT INTO chat_messages (id, fan_id, persona_id, direction, content, "
            "message_type, is_ai_generated, sentiment, intent, metadata_json, created_at) "
            "VALUES (:id, :fan_id, :pid, 'inbound', :content, 'text', 0, :sentiment, "
            ":intent, '{}', :now)"
        ),
        {
            "id": inbound_id, "fan_id": link.fan_id, "pid": str(persona.id),
            "content": text_in, "sentiment": reply.sentiment,
            "intent": reply.intent, "now": now,
        },
    )
    await db.execute(
        text(
            "INSERT INTO chat_messages (id, fan_id, persona_id, direction, content, "
            "message_type, is_ai_generated, sentiment, intent, metadata_json, created_at) "
            "VALUES (:id, :fan_id, :pid, 'outbound', :content, 'text', 1, :sentiment, "
            ":intent, :metadata, :now)"
        ),
        {
            "id": outbound_id, "fan_id": link.fan_id, "pid": str(persona.id),
            "content": reply.text, "sentiment": reply.sentiment,
            "intent": reply.intent,
            "metadata": json.dumps({
                "served_by": reply.served_by,
                "provider_chain": reply.provider_chain,
            }),
            "now": reply_at,
        },
    )
    await db.execute(
        text(
            "UPDATE fans SET messages_received = COALESCE(messages_received,0) + 1, "
            "messages_sent = COALESCE(messages_sent,0) + 1, "
            "last_message_at = :now, last_active = :now WHERE id = :fid"
        ),
        {"now": now, "fid": link.fan_id},
    )

    # First reply pins the conversation's provider, so every later reply in this
    # thread comes from the model that opened it.
    if not conversation.served_by and reply.served_by:
        conversation.served_by = reply.served_by
    conversation.updated_at = now

    await audit(
        db, "fan_message", user_id=user.id, actor="user",
        object_type="persona", object_id=str(persona.id),
        detail={
            "served_by": reply.served_by,
            "chain": reply.provider_chain,
            "intent": reply.intent,
        },
    )
    await db.commit()

    return {
        "reply": reply.text,
        "message_id": outbound_id,
        "intent": reply.intent,
        "sentiment": reply.sentiment,
        "suggests_ppv": reply.suggests_ppv,
        "ppv_prompt": reply.ppv_prompt if reply.suggests_ppv else "",
        # Who answered. The fan UI does not show this, but it is recorded and
        # returned rather than hidden, so a reply can always be traced to a
        # provider after the fact.
        "served_by": reply.served_by,
        "provider_chain": reply.provider_chain,
        "is_ai_generated": True,
        "created_at": now.isoformat(),
    }


# ── wallet ────────────────────────────────────────────────────────────

@router.get("/fan/wallet")
async def get_wallet(
    user: AppUser = Depends(require_user), db: AsyncSession = Depends(get_db)
):
    wallet = await _wallet(db, user.id)

    rows = (
        await db.execute(
            text(
                "SELECT t.id, t.kind, t.memo, t.created_at, "
                "COALESCE(SUM(CASE WHEN e.direction='credit' THEN e.amount_minor "
                "ELSE -e.amount_minor END), 0) AS net "
                "FROM ledger_transactions t "
                "JOIN ledger_entries e ON e.transaction_id = t.id "
                "WHERE e.account_code = :code "
                "GROUP BY t.id ORDER BY t.created_at DESC LIMIT 50"
            ),
            {"code": f"user:{user.id}:available"},
        )
    ).fetchall()

    return {
        "balance_minor": wallet.balance_minor or 0,
        "balance_display": f"{(wallet.balance_minor or 0) / 100:.2f}",
        "currency": wallet.currency or "USD",
        "simulated": True,
        "notice": SIMULATED_MONEY_NOTICE,
        "statement": [
            {
                "transaction_id": row[0],
                "kind": row[1],
                "memo": row[2],
                "amount_minor": int(row[4] or 0),
                "created_at": row[3].isoformat() if hasattr(row[3], "isoformat") else str(row[3]),
            }
            for row in rows
        ],
    }


class TopupRequest(BaseModel):
    amount_minor: int


@router.post("/fan/wallet/topup")
async def topup(
    payload: TopupRequest,
    user: AppUser = Depends(require_user),
    db: AsyncSession = Depends(get_db),
):
    """Add simulated funds. No card is collected and no real charge happens."""
    try:
        result = await billing.topup(
            db, user_id=user.id, amount_minor=payload.amount_minor
        )
    except billing.MoneyError as exc:
        raise HTTPException(
            400 if exc.code != "declined" else 402, str(exc)
        )
    await db.commit()

    wallet = await _wallet(db, user.id)
    return {
        **result,
        "balance_minor": wallet.balance_minor or 0,
        "notice": SIMULATED_MONEY_NOTICE,
    }


# ── products & content ────────────────────────────────────────────────

@router.get("/fan/products")
async def list_products(
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    rows = (
        await db.execute(
            select(Product)
            .where(Product.persona_id == str(link.persona_id),
                   Product.status == "published")
            .order_by(Product.price_minor, Product.created_at)
        )
    ).scalars().all()

    subscription = await active_subscription(db, user.id)
    products = []
    for product in rows:
        allowed, reason = await check_access(
            db, user_id=user.id, product=product
        )
        media_count = (
            await db.execute(
                select(func.count()).select_from(ProductMedia).where(
                    ProductMedia.product_id == product.id
                )
            )
        ).scalar() or 0
        products.append({
            "id": product.id,
            "title": product.title,
            "description": product.description or "",
            "price_minor": product.price_minor,
            "price_display": f"{product.price_minor / 100:.2f}",
            "kind": product.kind,
            "is_adult": bool(product.is_adult),
            "unlocked": allowed,
            "reason": reason,
            "min_tier_rank": product.min_tier_rank,
            "media_count": media_count,
            "cover_url": f"/api/v1/fan/content/{product.id}/media/0" if media_count else "",
        })

    return {
        "products": products,
        "subscription": (
            {"plan_code": subscription.plan_code, "rank": subscription.plan_rank}
            if subscription else None
        ),
        "disclosure": AI_DISCLOSURE,
    }


@router.post("/fan/products/{product_id}/unlock")
async def unlock(
    product_id: str,
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    """Buy one product. Clicking twice charges once."""
    product = await _product(db, product_id)

    try:
        result = await billing.unlock_ppv(
            db, user_id=user.id, product=product, fan_id=link.fan_id
        )
    except billing.MoneyError as exc:
        if exc.code == "insufficient_funds":
            raise HTTPException(402, str(exc))
        raise HTTPException(400, str(exc))

    await db.commit()
    wallet = await _wallet(db, user.id)
    return {
        **result,
        "balance_minor": wallet.balance_minor or 0,
        "unlocked": True,
        "media_url": f"/api/v1/fan/content/{product.id}/media/0",
    }


@router.get("/fan/content/{product_id}")
async def get_content(
    product_id: str,
    user: AppUser = Depends(require_user),
    db: AsyncSession = Depends(get_db),
):
    product = await _product(db, product_id)
    allowed, reason = await check_access(db, user_id=user.id, product=product)
    await _log_access(
        db, user_id=user.id, product_id=product.id,
        allowed=allowed, reason=reason,
    )
    await db.commit()

    if not allowed:
        raise HTTPException(402, "Not unlocked")

    media = (
        await db.execute(
            select(ProductMedia)
            .where(ProductMedia.product_id == product.id)
            .order_by(ProductMedia.position, ProductMedia.created_at)
        )
    ).scalars().all()

    return {
        "id": product.id,
        "title": product.title,
        "description": product.description or "",
        "kind": product.kind,
        "disclosure": AI_DISCLOSURE,
        "media": [
            {
                "index": index,
                "caption": item.caption or "",
                "url": f"/api/v1/fan/content/{product.id}/media/{index}",
            }
            for index, item in enumerate(media)
        ],
    }


@router.get("/fan/content/{product_id}/media/{index}")
async def serve_media(
    product_id: str,
    index: int,
    user: AppUser = Depends(require_user),
    db: AsyncSession = Depends(get_db),
):
    """Serve one file — but only if this user is entitled to it, right now.

    The entitlement is re-checked on every request rather than trusted from the
    listing page, and denials are logged. `private, no-store` keeps it out of
    shared caches, because the same URL is a 402 for the next person.
    """
    product = await _product(db, product_id)
    allowed, reason = await check_access(db, user_id=user.id, product=product)
    await _log_access(
        db, user_id=user.id, product_id=product.id,
        allowed=allowed, reason=reason,
    )
    await db.commit()

    if not allowed:
        raise HTTPException(402, "Not unlocked")

    media = (
        await db.execute(
            select(ProductMedia)
            .where(ProductMedia.product_id == product.id)
            .order_by(ProductMedia.position, ProductMedia.created_at)
        )
    ).scalars().all()

    if index < 0 or index >= len(media):
        raise HTTPException(404, "No such item")

    item = media[index]
    file_path = (STORAGE_DIR / item.rel_path).resolve()

    # Path traversal guard. rel_path comes from the database, but it is written
    # by a seed script and could be edited, so the resolved path is checked to
    # still be inside storage/ before anything is opened.
    if not str(file_path).startswith(str(STORAGE_DIR.resolve())):
        raise HTTPException(403, "Refusing to serve a path outside storage")
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(404, "The file for this item is missing")

    media_type = {
        ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".webp": "image/webp", ".mp4": "video/mp4",
    }.get(file_path.suffix.lower(), "application/octet-stream")

    return FileResponse(
        file_path,
        media_type=media_type,
        headers={
            "Cache-Control": "private, no-store",
            "X-AI-Generated": "true",
            "X-Simulated-Purchase": "true",
        },
    )


# ── subscriptions ─────────────────────────────────────────────────────

@router.get("/fan/subscription/plans")
async def list_plans(db: AsyncSession = Depends(get_db)):
    plans = (
        await db.execute(
            select(SubscriptionPlan)
            .where(SubscriptionPlan.active.is_(True))
            .order_by(SubscriptionPlan.rank)
        )
    ).scalars().all()
    return {
        "plans": [
            {
                "code": plan.code,
                "name": plan.name,
                "price_minor": plan.price_minor,
                "price_display": f"{plan.price_minor / 100:.2f}",
                "period_days": plan.period_days,
                "rank": plan.rank,
                "perks": plan.perks or "",
            }
            for plan in plans
        ],
        "simulated": True,
        "notice": SIMULATED_MONEY_NOTICE,
    }


class SubscribeRequest(BaseModel):
    plan_code: str


@router.post("/fan/subscription")
async def subscribe(
    payload: SubscribeRequest,
    user: AppUser = Depends(require_user),
    link: FanAccount = Depends(require_fan),
    db: AsyncSession = Depends(get_db),
):
    plan = (
        await db.execute(
            select(SubscriptionPlan).where(
                SubscriptionPlan.code == payload.plan_code,
                SubscriptionPlan.active.is_(True),
            )
        )
    ).scalar_one_or_none()
    if plan is None:
        raise HTTPException(404, "No such plan")

    try:
        result = await billing.subscribe(
            db, user_id=user.id, plan=plan, fan_id=link.fan_id
        )
    except billing.MoneyError as exc:
        if exc.code == "insufficient_funds":
            raise HTTPException(402, str(exc))
        raise HTTPException(400, str(exc))
    await db.commit()

    wallet = await _wallet(db, user.id)
    return {**result, "balance_minor": wallet.balance_minor or 0}


# ── activity ──────────────────────────────────────────────────────────

@router.get("/fan/activity")
async def activity(
    user: AppUser = Depends(require_user), db: AsyncSession = Depends(get_db)
):
    """Everything this account has done, in order, with times."""
    events = (
        await db.execute(
            select(AuditEvent)
            .where(AuditEvent.user_id == user.id)
            .order_by(AuditEvent.created_at.desc())
            .limit(100)
        )
    ).scalars().all()

    accesses = (
        await db.execute(
            select(AccessEvent)
            .where(AccessEvent.user_id == user.id)
            .order_by(AccessEvent.created_at.desc())
            .limit(100)
        )
    ).scalars().all()

    return {
        "events": [
            {
                "action": event.action,
                "actor": event.actor,
                "object_type": event.object_type,
                "object_id": event.object_id,
                "detail": event.detail or {},
                "created_at": (
                    event.created_at.isoformat() if event.created_at else None
                ),
            }
            for event in events
        ],
        "accesses": [
            {
                "product_id": event.product_id,
                "allowed": bool(event.allowed),
                "reason": event.reason,
                "created_at": (
                    event.created_at.isoformat() if event.created_at else None
                ),
            }
            for event in accesses
        ],
    }
