#!/bin/bash
# ═══════════════════════════════════════════════════════════
# Persona Studio — EC2 Deployment Script
# Paste this entire block into your EC2 terminal.
# ═══════════════════════════════════════════════════════════
set -e

echo "╔══════════════════════════════════════╗"
echo "║  PERSONA STUDIO — EC2 DEPLOY         ║"
echo "╚══════════════════════════════════════╝"

# ─── 1. System Info ──────────────────────────────────────
echo ""
echo "=== SYSTEM INFO ==="
echo "OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')"
echo "CPU: $(nproc) cores"
echo "RAM: $(free -h | awk '/Mem:/ {print $2}')"
echo "Disk: $(df -h / | awk 'NR==2 {print $4}') free"
echo ""

# ─── 2. Install Dependencies ─────────────────────────────
echo "=== Installing dependencies ==="
dnf update -y -q 2>/dev/null || yum update -y -q 2>/dev/null
dnf install -y git curl wget unzip docker python3 python3-pip -q 2>/dev/null || \
yum install -y git curl wget unzip docker python3 python3-pip -q 2>/dev/null

# ─── 3. Start Docker ─────────────────────────────────────
echo "=== Starting Docker ==="
systemctl enable docker
systemctl start docker
echo "Docker: $(docker --version)"

# ─── 4. Install Docker Compose if missing ────────────────
if ! docker compose version &>/dev/null; then
    echo "=== Installing Docker Compose ==="
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
        -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
fi
echo "Compose: $(docker compose version)"

# ─── 5. Clone or update Persona Studio ───────────────────
APP_DIR="/opt/persona-studio"

if [ -d "$APP_DIR/.git" ]; then
    echo "=== Updating existing repo ==="
    cd $APP_DIR
    git pull
else
    echo "=== Cloning Persona Studio ==="
    rm -rf $APP_DIR
    # If the zip was uploaded, use that; otherwise git clone
    if [ -f "/home/ec2-user/persona-studio-starter.zip" ]; then
        mkdir -p $APP_DIR
        unzip -q /home/ec2-user/persona-studio-starter.zip -d $APP_DIR
        cd $APP_DIR
        # If zip created a subdirectory, move contents up
        if [ -d "persona-studio-starter" ]; then
            mv persona-studio-starter/* .
            mv persona-studio-starter/.* . 2>/dev/null
            rmdir persona-studio-starter
        fi
    elif [ -f "/home/ec2-user/persona-studio.zip" ]; then
        mkdir -p $APP_DIR
        unzip -q /home/ec2-user/persona-studio.zip -d $APP_DIR
        cd $APP_DIR
    else
        echo "No upload found. Using git clone (if available)."
        git clone https://github.com/placeholder/persona-studio.git $APP_DIR 2>/dev/null || {
            echo "ERROR: No source found. Upload the zip first:"
            echo "  scp -i key.pem persona-studio.zip ec2-user@IP:/home/ec2-user/"
            exit 1
        }
        cd $APP_DIR
    fi
fi

echo "App dir: $(pwd)"

# ─── 6. Configure Environment ────────────────────────────
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "localhost")

cat > .env << EOF
# Persona Studio — EC2 Configuration
# Generated by deploy-ec2.sh on $(date)

# ─── Database ────────────────────────────────────────────
POSTGRES_USER=persona
POSTGRES_PASSWORD=persona_secret
POSTGRES_DB=persona_studio

# ─── Object Storage ──────────────────────────────────────
MINIO_ACCESS_KEY=persona
MINIO_SECRET_KEY=persona_secret
MINIO_BUCKET=persona-studio

# ─── Provider Registry ───────────────────────────────────
# mock = deterministic mocks (no GPU needed)
# hybrid = real where available, mock elsewhere
PROVIDER_REGISTRY=mock

# ─── External Providers (fill in when ready) ─────────────
COMFYUI_URL=
WAN_VIDEO_URL=
ELEVENLABS_API_KEY=
GPU_WORKER_URL=
OLLAMA_URL=

# ─── Frontend ────────────────────────────────────────────
NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}:8000

# ─── Ports ───────────────────────────────────────────────
API_PORT=8000
WEB_PORT=3000
EOF

echo "=== Environment configured ==="
echo "Public IP: $PUBLIC_IP"
echo "Frontend: http://${PUBLIC_IP}:3000"
echo "API Docs: http://${PUBLIC_IP}:8000/docs"

# ─── 7. Build and Start ─────────────────────────────────
echo ""
echo "=== Building containers (this takes a few minutes) ==="
docker compose build --no-cache

echo ""
echo "=== Starting Persona Studio ==="
docker compose up -d

# ─── 8. Wait for Health ──────────────────────────────────
echo ""
echo "=== Waiting for services to be healthy ==="
for i in $(seq 1 30); do
    if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
        echo "✅ API is healthy!"
        break
    fi
    echo "  Waiting... ($i/30)"
    sleep 5
done

# ─── 9. Status ───────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  PERSONA STUDIO — DEPLOYMENT COMPLETE            ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
docker compose ps
echo ""
echo "  Frontend:  http://${PUBLIC_IP}:3000"
echo "  API:       http://${PUBLIC_IP}:8000"
echo "  API Docs:  http://${PUBLIC_IP}:8000/docs"
echo "  MinIO:     http://${PUBLIC_IP}:9001"
echo ""
echo "  Logs:      docker compose logs -f"
echo "  Stop:      docker compose down"
echo "  Restart:   docker compose restart"
echo ""
echo "⚠  IMPORTANT: Add inbound rules to your EC2 security group:"
echo "    TCP 3000 — Source: My IP"
echo "    TCP 8000 — Source: My IP"
echo ""
